#!/bin/bash

# For Intel/AMD GPUs one uses the open-source mesa drivers
sudo apt update
#sudo apt install mesa-vulkan-drivers mesa-utils mesa-vulkan-drivers:i386 libvulkan1 libvulkan1:i386
sudo apt -t bookworm-backports install mesa-vulkan-drivers mesa-vulkan-drivers:i386 -y

