#!/bin/bash
set -e

# share clipboard with system
sudo apt install xclip

if [ ! -d ~/.vim/pack/themes/start ]; then
  mkdir -p ~/.vim/pack/themes/start
fi

if [ ! -d ~/.vim/pack/themes/start/dracula ]; then
  git clone https://github.com/dracula/vim.git  ~/.vim/pack/themes/start/dracula
fi

cp -f vimrc ~/.vimrc

